### ISSUE TITLE
unlisted dependancy: haven

### ISSUE THREAD

**Issue by kjewell** [fhmcguire/NSDUH-complex-sample-analysis-tutorial#1]
I believe the tutorial has an unloaded dependency of library(haven).
(or at least, adding that line fixed the error I was getting.)

Thanks for creating this document.

**Comment by fhmcguire** [comment]
Thanks for alerting me! Which section of the code was causing the issue?

**Comment by kjewell** [comment]
Lines 101-103
> # set invalid responses to missing (NA)
> nsduh <- nsduh %>% 
+   replace_with_na(replace = list(sexident = c(85, 89, 94, 97, 98, 99))) %>% 
+   replace_with_na(replace = list(anyhlti2 = c(94, 97, 98)))
Error in `as.character()`:
! Can't convert `x` <haven_labelled> to <character>.
Backtrace:
  1. ... %>% ...
  5. naniar:::replace_with_na.data.frame(...)
  9. data[[var]] %in% unlist(new_replace[[var]])
 11. base::mtfrm.default(`<hvn_lbll>`)
 13. vctrs:::as.character.vctrs_vctr(x)

**Comment by fhmcguire** [comment]
Got it! Thanks. I'll update the repo now.
